image: maven:3.9.6-eclipse-temurin-17

stages:
  - build
  - dockerize

cache:
  paths:
    - .m2/repository

build:
  stage: build
  script:
    - mvn clean package -DskipTests
  artifacts:
    paths:
      - target/*.jar

dockerize:
  stage: dockerize
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build --build-arg MONGO_DATABASE=$MONGO_DATABASE --build-arg MONGO_USER=$MONGO_USER --build-arg MONGO_PASSWORD=$MONGO_PASSWORD --build-arg MONGO_CLUSTER=$MONGO_CLUSTER --build-arg SECRET_KEY=$SECRET_KEY -t $CI_REGISTRY_IMAGE:latest .
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE:latest
  only:
    - main
